version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: medicsys-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 030762
      POSTGRES_DB: medicsys
    ports:
      - "5432:5432"
    volumes:
      - medicsys_pgdata:/var/lib/postgresql

volumes:
  medicsys_pgdata:
